#include "p16F628a.inc"
 __CONFIG _FOSC_INTOSCCLK & _WDTE_OFF & _PWRTE_OFF & _MCLRE_OFF & _BOREN_OFF & _LVP_OFF & _CPD_OFF & _CP_OFF      
RES_VECT  CODE    0x0000
GOTO START
MAIN_PROG CODE

N1 EQU 0x30
N2 EQU 0x31
RE EQU 0x32

START:
MOVLW 0x07
MOVWF CMCON
BCF STATUS, RP1
BSF STATUS, RP0
MOVLW B'00000000'
MOVWF TRISB
BCF STATUS, RP0
GOTO INICIAL
    
INICIAL:
MOVFW PORTA
MOVWF N1
MOVWF N2
BCF N1, 7
BCF N1, 6
BCF N1, 5
BCF N1, 4
BCF N2, 3
BCF N2, 2
BCF N2, 1
BCF N2, 0
SWAPF N2
MOVLW D'0'
	 
MULTIPLICACION:
ADDWF N1, 0
DECFSZ N2
GOTO MULTIPLICACION
MOVWF RE 
MOVFW RE
MOVWF PORTB

END